const STOCK_API_URL='https://script.google.com/macros/s/AKfycbw6CiFU3gHuwHPby3zXv9hCcGIF0HxWDLOroNsRt7apvHM5BvPzrfOD1MA1VAyP0o-z/exec';
const AIRMQ_URL='https://api.airmq.cc/';
const AIRMQ_LOCATION_ID='BY042010279';
const TREATMENTS_API_URL='https://script.google.com/macros/s/AKfycbziEuAPz4Kvg9GsvdSyKytYVEHSe2gcoSEmwKhp0unOVNm5OPdUYJf33mqn2qgDEZVd/exec';
const defaultMeasurements=[{pressure:3,flow:0.635},{pressure:4,flow:0.75},{pressure:5,flow:0.86}];
const defaultBlocks=[{id:id(),name:'Яблоня около навеса 0',culture:'Яблоня',area:7.5}];
let appState={activeTab:'calc',measurements:defaultMeasurements,blocks:defaultBlocks,treatmentRows:[],treatmentGroups:[],filteredTreatmentGroups:[],stockRaw:[],stockFiltered:[]};
const els={};
document.addEventListener('DOMContentLoaded',()=>{bind();events();renderTabs();renderBlockSelect();calculate();loadTreatments();});
function bind(){['menuButton','closeMenuButton','sidePanel','overlay','blockSelect','cultureInput','areaInput','normInput','speedInput','spacingInput','nozzlesInput','tankInput','resultCulture','resultArea','resultLiters','resultTanks','resultTotalFlow','resultFlowPerNozzle','resultPressure','pressureStatus','pressureLower','pressureUpper','measurementPressure','measurementFlow','measurementsBody','saveMeasurementBtn','blockName','blockCulture','blockYear','blockRows','blockScheme','blockCount','blockArea','saveBlockBtn','blocksBody','blockEditNotice','weatherCity','weatherLat','weatherLon','weatherLoadBtn','weatherPlace','weatherStatus','weatherCards','stockBody','stockStatus','stockTypeFilter','stockSortBy','airReloadBtn','airInfo','airStatus','airTemp','airHum','airPms1','airPms25','airPms10','airTime','treatmentsStatus','treatmentPlaceFilter','treatmentChemFilter','treatmentTypeFilter','lastTreatment','treatmentsDays'].forEach(id=>els[id]=document.getElementById(id));}
function events(){document.querySelectorAll('.tab-btn').forEach(btn=>btn.addEventListener('click',()=>{appState.activeTab=btn.dataset.tab;renderTabs();}));['cultureInput','areaInput','normInput','speedInput','spacingInput','nozzlesInput','tankInput'].forEach(id=>els[id].addEventListener('input',calculate));els.blockSelect.addEventListener('change',()=>{const b=getSelectedBlock();els.cultureInput.value=b.culture||'';els.areaInput.value=b.area||'';calculate();});els.treatmentPlaceFilter.addEventListener('change',applyTreatmentFilters);els.treatmentChemFilter.addEventListener('change',applyTreatmentFilters);els.treatmentTypeFilter.addEventListener('change',applyTreatmentFilters);}
function renderTabs(){document.querySelectorAll('.tab-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===appState.activeTab));document.querySelectorAll('.tab-content').forEach(sec=>sec.classList.remove('active'));document.getElementById('tab-'+appState.activeTab).classList.add('active');}
function renderBlockSelect(){els.blockSelect.innerHTML='';appState.blocks.forEach(b=>{const opt=document.createElement('option');opt.value=b.id;opt.textContent=b.name;els.blockSelect.appendChild(opt);});const b=getSelectedBlock();els.cultureInput.value=b.culture||'';els.areaInput.value=b.area||'';}
function getSelectedBlock(){return appState.blocks.find(b=>String(b.id)===String(els.blockSelect.value))||appState.blocks[0];}
function calculate(){const culture=els.cultureInput.value||'—',area=toNum(els.areaInput.value),norm=toNum(els.normInput.value),speed=toNum(els.speedInput.value),spacing=toNum(els.spacingInput.value),nozzles=toNum(els.nozzlesInput.value),tank=toNum(els.tankInput.value);const totalLiters=area*norm,totalFlow=speed>0&&spacing>0?(norm*speed*spacing)/600:0,flowPerNozzle=nozzles>0?totalFlow/nozzles:0;els.resultCulture.textContent=culture;els.resultArea.textContent=`${fmt(area,2)} га`;els.resultLiters.textContent=`${fmt(totalLiters,0)} л`;els.resultTanks.textContent=tank>0?fmt(totalLiters/tank,2):'—';els.resultTotalFlow.textContent=`${fmt(totalFlow,3)} л/мин`;els.resultFlowPerNozzle.textContent=`${fmt(flowPerNozzle,3)} л/мин`;els.resultPressure.textContent='—';}
async function loadTreatments(){els.treatmentsStatus.textContent='Загрузка обработок...';try{const resp=await fetch(TREATMENTS_API_URL);const raw=await resp.json();const rows=Array.isArray(raw)?raw:(raw.data||[]);appState.treatmentRows=(rows||[]).map(x=>({treatmentNumber:String(x.treatmentNumber??'').trim(),date:String(x.date??'').trim(),worker:String(x.worker??'').trim(),place:String(x.place??'').trim(),method:String(x.method??'').trim(),tankLiters:x.tankLiters??'',tankUnit:String(x.tankUnit??'').trim(),chemType:String(x.chemType??'').trim(),chemical:String(x.chemical??'').trim(),amount:x.amount??'',amountUnit:String(x.amountUnit??'').trim()})).filter(x=>x.treatmentNumber||x.chemical);appState.treatmentGroups=buildTreatmentGroups(appState.treatmentRows);renderTreatmentFilters();applyTreatmentFilters();}catch(e){els.treatmentsStatus.textContent='Ошибка загрузки обработок: '+e.message;}}
function buildTreatmentGroups(rows){const map=new Map();rows.forEach(row=>{const n=String(row.treatmentNumber||'').trim();if(!n)return;if(!map.has(n)){map.set(n,{treatmentNumber:n,date:row.date||'',worker:row.worker||'',place:row.place||'',method:row.method||'',tankLiters:row.tankLiters||'',tankUnit:row.tankUnit||'',chemicals:[]});}const g=map.get(n);if(row.chemical||row.chemType||row.amount!==''||row.amountUnit){g.chemicals.push({chemType:row.chemType||'',chemical:row.chemical||'',amount:row.amount||'',amountUnit:row.amountUnit||''});}});return Array.from(map.values()).sort((a,b)=>String(b.date).localeCompare(String(a.date)));}
function renderTreatmentFilters(){fillSelect(els.treatmentPlaceFilter,'Все участки',[...new Set(appState.treatmentGroups.map(x=>x.place).filter(Boolean))]);fillSelect(els.treatmentChemFilter,'Вся химия',[...new Set(appState.treatmentGroups.flatMap(x=>x.chemicals.map(c=>c.chemical)).filter(Boolean))]);fillSelect(els.treatmentTypeFilter,'Все виды',[...new Set(appState.treatmentGroups.flatMap(x=>x.chemicals.map(c=>c.chemType)).filter(Boolean))]);}
function fillSelect(select,label,items){select.innerHTML='';const first=document.createElement('option');first.value='all';first.textContent=label;select.appendChild(first);items.sort((a,b)=>String(a).localeCompare(String(b),'ru')).forEach(item=>{const opt=document.createElement('option');opt.value=item;opt.textContent=item;select.appendChild(opt);});}
function applyTreatmentFilters(){const place=els.treatmentPlaceFilter.value||'all',chem=els.treatmentChemFilter.value||'all',type=els.treatmentTypeFilter.value||'all';let groups=[...appState.treatmentGroups];if(place!=='all')groups=groups.filter(x=>x.place===place);if(chem!=='all')groups=groups.filter(x=>x.chemicals.some(c=>c.chemical===chem));if(type!=='all')groups=groups.filter(x=>x.chemicals.some(c=>c.chemType===type));appState.filteredTreatmentGroups=groups;renderLastTreatment();renderTreatmentDays();els.treatmentsStatus.textContent=`Обработок: ${groups.length}`;}
function renderLastTreatment(){if(!appState.filteredTreatmentGroups.length){els.lastTreatment.textContent='Нет данных';return;}const t=appState.filteredTreatmentGroups[0];const chemText=t.chemicals.map(c=>`${c.chemical}${c.chemType?' ('+c.chemType+')':''}${c.amount!==''?' — '+c.amount+' '+c.amountUnit:''}`).join('; ');els.lastTreatment.textContent=`${t.date} · № ${t.treatmentNumber} · ${t.place} · ${t.worker} · ${t.method} · вода: ${t.tankLiters} ${t.tankUnit} · ${chemText}`;}
function renderTreatmentDays(){els.treatmentsDays.innerHTML='';if(!appState.filteredTreatmentGroups.length){els.treatmentsDays.textContent='Нет обработок по выбранному фильтру.';return;}const byDate={};appState.filteredTreatmentGroups.forEach(g=>{const key=g.date||'Без даты';if(!byDate[key])byDate[key]=[];byDate[key].push(g);});Object.keys(byDate).sort((a,b)=>String(b).localeCompare(String(a))).forEach(date=>{const day=document.createElement('div');day.className='day';day.innerHTML=`<div><strong>${escapeHtml(date)}</strong></div>`;byDate[date].forEach(g=>{const item=document.createElement('div');item.className='item';const chems=g.chemicals.map(c=>`${escapeHtml(c.chemical)}${c.chemType?' ('+escapeHtml(c.chemType)+')':''}${c.amount!==''?' — '+escapeHtml(String(c.amount))+' '+escapeHtml(c.amountUnit):''}`).join('<br>');item.innerHTML=`<div><strong>№ ${escapeHtml(g.treatmentNumber)}</strong> · ${escapeHtml(g.place)}</div><div>${escapeHtml(g.worker)} · ${escapeHtml(g.method)} · вода: ${escapeHtml(String(g.tankLiters))} ${escapeHtml(g.tankUnit)}</div><div>${chems}</div>`;day.appendChild(item);});els.treatmentsDays.appendChild(day);});}
function toNum(v){if(v===null||v===undefined||v==='')return 0;return Number(String(v).replace(',','.'));}function fmt(v,d=2){const n=toNum(v);return isFinite(n)?n.toFixed(d):'—';}
function load(k,f){try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw):f}catch{return f}}
function id(){return Math.random().toString(36).slice(2,10)}
function escapeHtml(t){return String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('\"','&quot;').replaceAll(\"'\",'&#039;')}
